import { CanvasTemplate } from "./types";

// Default Idea Canvas template with 3 columns: Idea, Description, Impact
export const DEFAULT_IDEA_TEMPLATE: CanvasTemplate = {
  id: "idea-canvas",
  name: "Idea Canvas",
  description: "Default canvas with Idea, Description, and Impact columns",
  elements: [
    // Idea column
    {
      type: "frame",
      position: { x: 60, y: 60 },
      size: { width: 320, height: 420 },
      rotation: 0,
      zIndex: 1,
      locked: false,
      visible: true,
      data: { title: "Idea", backgroundColor: "rgba(139, 92, 246, 0.15)" },
    },
    // Description column
    {
      type: "frame",
      position: { x: 400, y: 60 },
      size: { width: 320, height: 420 },
      rotation: 0,
      zIndex: 1,
      locked: false,
      visible: true,
      data: {
        title: "Description",
        backgroundColor: "rgba(107, 114, 128, 0.15)",
      },
    },
    // Impact column
    {
      type: "frame",
      position: { x: 740, y: 60 },
      size: { width: 320, height: 420 },
      rotation: 0,
      zIndex: 1,
      locked: false,
      visible: true,
      data: { title: "Impact", backgroundColor: "rgba(20, 184, 166, 0.15)" },
    },
  ],
};

export const CANVAS_TEMPLATES: CanvasTemplate[] = [
  DEFAULT_IDEA_TEMPLATE,
  {
    id: "kanban",
    name: "Kanban Board",
    description: "Organize tasks in columns: Backlog, In Progress, Done",
    elements: [
      // Column headers
      {
        type: "frame",
        position: { x: 50, y: 50 },
        size: { width: 280, height: 500 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { title: "Backlog", backgroundColor: "rgba(239, 68, 68, 0.1)" },
      },
      {
        type: "frame",
        position: { x: 350, y: 50 },
        size: { width: 280, height: 500 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          title: "In Progress",
          backgroundColor: "rgba(245, 158, 11, 0.1)",
        },
      },
      {
        type: "frame",
        position: { x: 650, y: 50 },
        size: { width: 280, height: 500 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { title: "Done", backgroundColor: "rgba(34, 197, 94, 0.1)" },
      },
      // Sample cards
      {
        type: "card",
        position: { x: 70, y: 100 },
        size: { width: 240, height: 100 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          title: "Task 1",
          description: "Description of task 1",
          color: "#EF4444",
          tags: [{ label: "Feature", color: "#3B82F6" }],
          priority: "high",
        },
      },
      {
        type: "card",
        position: { x: 70, y: 220 },
        size: { width: 240, height: 100 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          title: "Task 2",
          description: "Description of task 2",
          color: "#F59E0B",
          tags: [{ label: "Bug", color: "#EF4444" }],
          priority: "medium",
        },
      },
      {
        type: "card",
        position: { x: 370, y: 100 },
        size: { width: 240, height: 100 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          title: "Task 3",
          description: "Currently working on this",
          color: "#F59E0B",
          tags: [{ label: "Enhancement", color: "#8B5CF6" }],
          priority: "medium",
        },
      },
    ],
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Horizontal timeline with milestones and dates",
    elements: [
      // Title
      {
        type: "text",
        position: { x: 50, y: 30 },
        size: { width: 300, height: 40 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          content: "Project Timeline",
          fontSize: 24,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#1F2937",
          align: "left",
        },
      },
      // Timeline line
      {
        type: "line",
        position: { x: 50, y: 200 },
        size: { width: 900, height: 4 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          orientation: "horizontal",
          color: "#3B82F6",
          strokeWidth: 4,
          style: "solid",
        },
      },
      // Milestone 1
      {
        type: "shape",
        position: { x: 100, y: 185 },
        size: { width: 30, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          shapeType: "circle",
          fill: "#3B82F6",
          stroke: "#1E40AF",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 70, y: 230 },
        size: { width: 100, height: 20 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Phase 1",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#1F2937",
          align: "center",
        },
      },
      {
        type: "sticky-note",
        position: { x: 50, y: 100 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Planning & Research",
          color: "#DBEAFE",
          fontSize: 12,
        },
      },
      // Milestone 2
      {
        type: "shape",
        position: { x: 350, y: 185 },
        size: { width: 30, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          shapeType: "circle",
          fill: "#10B981",
          stroke: "#059669",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 320, y: 230 },
        size: { width: 100, height: 20 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Phase 2",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#1F2937",
          align: "center",
        },
      },
      {
        type: "sticky-note",
        position: { x: 300, y: 100 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: { content: "Development", color: "#D1FAE5", fontSize: 12 },
      },
      // Milestone 3
      {
        type: "shape",
        position: { x: 600, y: 185 },
        size: { width: 30, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          shapeType: "circle",
          fill: "#F59E0B",
          stroke: "#D97706",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 570, y: 230 },
        size: { width: 100, height: 20 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Phase 3",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#1F2937",
          align: "center",
        },
      },
      {
        type: "sticky-note",
        position: { x: 550, y: 100 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: { content: "Testing & QA", color: "#FEF3C7", fontSize: 12 },
      },
      // Milestone 4
      {
        type: "shape",
        position: { x: 850, y: 185 },
        size: { width: 30, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          shapeType: "circle",
          fill: "#8B5CF6",
          stroke: "#7C3AED",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 820, y: 230 },
        size: { width: 100, height: 20 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Launch",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#1F2937",
          align: "center",
        },
      },
      {
        type: "sticky-note",
        position: { x: 800, y: 100 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: { content: "Release & Deploy", color: "#EDE9FE", fontSize: 12 },
      },
    ],
  },
  {
    id: "priority-matrix",
    name: "Priority Matrix",
    description: "2x2 matrix for prioritizing tasks (Urgent/Important)",
    elements: [
      // Title
      {
        type: "text",
        position: { x: 300, y: 20 },
        size: { width: 300, height: 40 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          content: "Priority Matrix",
          fontSize: 24,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#1F2937",
          align: "center",
        },
      },
      // Quadrant labels - Y axis
      {
        type: "text",
        position: { x: 20, y: 150 },
        size: { width: 80, height: 60 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          content: "Important",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#6B7280",
          align: "center",
        },
      },
      {
        type: "text",
        position: { x: 20, y: 400 },
        size: { width: 80, height: 60 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          content: "Not Important",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#6B7280",
          align: "center",
        },
      },
      // Quadrant labels - X axis
      {
        type: "text",
        position: { x: 200, y: 580 },
        size: { width: 100, height: 30 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          content: "Urgent",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#6B7280",
          align: "center",
        },
      },
      {
        type: "text",
        position: { x: 500, y: 580 },
        size: { width: 100, height: 30 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          content: "Not Urgent",
          fontSize: 14,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#6B7280",
          align: "center",
        },
      },
      // Quadrants
      {
        type: "frame",
        position: { x: 100, y: 70 },
        size: { width: 280, height: 240 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { title: "DO FIRST", backgroundColor: "rgba(239, 68, 68, 0.15)" },
      },
      {
        type: "frame",
        position: { x: 400, y: 70 },
        size: { width: 280, height: 240 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          title: "SCHEDULE",
          backgroundColor: "rgba(59, 130, 246, 0.15)",
        },
      },
      {
        type: "frame",
        position: { x: 100, y: 330 },
        size: { width: 280, height: 240 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          title: "DELEGATE",
          backgroundColor: "rgba(245, 158, 11, 0.15)",
        },
      },
      {
        type: "frame",
        position: { x: 400, y: 330 },
        size: { width: 280, height: 240 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          title: "ELIMINATE",
          backgroundColor: "rgba(107, 114, 128, 0.15)",
        },
      },
    ],
  },
  {
    id: "brainstorm",
    name: "Brainstorm",
    description: "Free-form brainstorming with central topic",
    elements: [
      // Central topic
      {
        type: "sticky-note",
        position: { x: 350, y: 250 },
        size: { width: 200, height: 150 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Main Topic\n\nWhat are we brainstorming?",
          color: "#FCE7F3",
          fontSize: 14,
        },
      },
      // Surrounding ideas
      {
        type: "sticky-note",
        position: { x: 100, y: 100 },
        size: { width: 180, height: 120 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { content: "Idea 1", color: "#FEF3C7", fontSize: 14 },
      },
      {
        type: "sticky-note",
        position: { x: 350, y: 50 },
        size: { width: 180, height: 120 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { content: "Idea 2", color: "#DBEAFE", fontSize: 14 },
      },
      {
        type: "sticky-note",
        position: { x: 600, y: 100 },
        size: { width: 180, height: 120 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { content: "Idea 3", color: "#D1FAE5", fontSize: 14 },
      },
      {
        type: "sticky-note",
        position: { x: 100, y: 350 },
        size: { width: 180, height: 120 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { content: "Idea 4", color: "#EDE9FE", fontSize: 14 },
      },
      {
        type: "sticky-note",
        position: { x: 600, y: 350 },
        size: { width: 180, height: 120 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { content: "Idea 5", color: "#FFEDD5", fontSize: 14 },
      },
    ],
  },
  {
    id: "flowchart",
    name: "Flowchart",
    description: "Process flow with decision points",
    elements: [
      // Start
      {
        type: "shape",
        position: { x: 350, y: 50 },
        size: { width: 120, height: 60 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          shapeType: "rectangle",
          fill: "#10B981",
          stroke: "#059669",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 370, y: 70 },
        size: { width: 80, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Start",
          fontSize: 16,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#FFFFFF",
          align: "center",
        },
      },
      // Process 1
      {
        type: "shape",
        position: { x: 350, y: 150 },
        size: { width: 120, height: 60 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          shapeType: "rectangle",
          fill: "#3B82F6",
          stroke: "#1E40AF",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 360, y: 170 },
        size: { width: 100, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Process 1",
          fontSize: 14,
          fontWeight: "normal",
          fontFamily: "Inter, sans-serif",
          color: "#FFFFFF",
          align: "center",
        },
      },
      // Decision
      {
        type: "shape",
        position: { x: 360, y: 260 },
        size: { width: 100, height: 100 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          shapeType: "diamond",
          fill: "#F59E0B",
          stroke: "#D97706",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 370, y: 295 },
        size: { width: 80, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Decision?",
          fontSize: 12,
          fontWeight: "normal",
          fontFamily: "Inter, sans-serif",
          color: "#FFFFFF",
          align: "center",
        },
      },
      // Yes path
      {
        type: "shape",
        position: { x: 550, y: 280 },
        size: { width: 120, height: 60 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          shapeType: "rectangle",
          fill: "#3B82F6",
          stroke: "#1E40AF",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 560, y: 300 },
        size: { width: 100, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Yes Path",
          fontSize: 14,
          fontWeight: "normal",
          fontFamily: "Inter, sans-serif",
          color: "#FFFFFF",
          align: "center",
        },
      },
      // No path
      {
        type: "shape",
        position: { x: 150, y: 280 },
        size: { width: 120, height: 60 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          shapeType: "rectangle",
          fill: "#3B82F6",
          stroke: "#1E40AF",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 160, y: 300 },
        size: { width: 100, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "No Path",
          fontSize: 14,
          fontWeight: "normal",
          fontFamily: "Inter, sans-serif",
          color: "#FFFFFF",
          align: "center",
        },
      },
      // End
      {
        type: "shape",
        position: { x: 350, y: 420 },
        size: { width: 120, height: 60 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          shapeType: "rectangle",
          fill: "#EF4444",
          stroke: "#DC2626",
          strokeWidth: 2,
        },
      },
      {
        type: "text",
        position: { x: 375, y: 440 },
        size: { width: 70, height: 30 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "End",
          fontSize: 16,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#FFFFFF",
          align: "center",
        },
      },
      // Connectors
      {
        type: "connector",
        position: { x: 410, y: 110 },
        size: { width: 10, height: 40 },
        rotation: 0,
        zIndex: 0,
        locked: false,
        visible: true,
        data: {
          startElementId: null,
          endElementId: null,
          startPoint: { x: 410, y: 110 },
          endPoint: { x: 410, y: 150 },
          lineType: "straight",
          arrowStart: false,
          arrowEnd: true,
          color: "#64748B",
          strokeWidth: 2,
        },
      },
      {
        type: "connector",
        position: { x: 410, y: 210 },
        size: { width: 10, height: 50 },
        rotation: 0,
        zIndex: 0,
        locked: false,
        visible: true,
        data: {
          startElementId: null,
          endElementId: null,
          startPoint: { x: 410, y: 210 },
          endPoint: { x: 410, y: 260 },
          lineType: "straight",
          arrowStart: false,
          arrowEnd: true,
          color: "#64748B",
          strokeWidth: 2,
        },
      },
      {
        type: "connector",
        position: { x: 410, y: 360 },
        size: { width: 10, height: 60 },
        rotation: 0,
        zIndex: 0,
        locked: false,
        visible: true,
        data: {
          startElementId: null,
          endElementId: null,
          startPoint: { x: 410, y: 360 },
          endPoint: { x: 410, y: 420 },
          lineType: "straight",
          arrowStart: false,
          arrowEnd: true,
          color: "#64748B",
          strokeWidth: 2,
        },
      },
    ],
  },
  {
    id: "swot",
    name: "SWOT Analysis",
    description: "Strengths, Weaknesses, Opportunities, Threats",
    elements: [
      // Title
      {
        type: "text",
        position: { x: 300, y: 20 },
        size: { width: 200, height: 40 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          content: "SWOT Analysis",
          fontSize: 24,
          fontWeight: "bold",
          fontFamily: "Inter, sans-serif",
          color: "#1F2937",
          align: "center",
        },
      },
      // Quadrants
      {
        type: "frame",
        position: { x: 50, y: 80 },
        size: { width: 350, height: 280 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          title: "Strengths",
          backgroundColor: "rgba(34, 197, 94, 0.15)",
        },
      },
      {
        type: "frame",
        position: { x: 420, y: 80 },
        size: { width: 350, height: 280 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          title: "Weaknesses",
          backgroundColor: "rgba(239, 68, 68, 0.15)",
        },
      },
      {
        type: "frame",
        position: { x: 50, y: 380 },
        size: { width: 350, height: 280 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: {
          title: "Opportunities",
          backgroundColor: "rgba(59, 130, 246, 0.15)",
        },
      },
      {
        type: "frame",
        position: { x: 420, y: 380 },
        size: { width: 350, height: 280 },
        rotation: 0,
        zIndex: 1,
        locked: false,
        visible: true,
        data: { title: "Threats", backgroundColor: "rgba(245, 158, 11, 0.15)" },
      },
      // Sample sticky notes
      {
        type: "sticky-note",
        position: { x: 70, y: 130 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: { content: "Add strength here", color: "#D1FAE5", fontSize: 12 },
      },
      {
        type: "sticky-note",
        position: { x: 440, y: 130 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: { content: "Add weakness here", color: "#FCE7F3", fontSize: 12 },
      },
      {
        type: "sticky-note",
        position: { x: 70, y: 430 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: {
          content: "Add opportunity here",
          color: "#DBEAFE",
          fontSize: 12,
        },
      },
      {
        type: "sticky-note",
        position: { x: 440, y: 430 },
        size: { width: 150, height: 80 },
        rotation: 0,
        zIndex: 2,
        locked: false,
        visible: true,
        data: { content: "Add threat here", color: "#FEF3C7", fontSize: 12 },
      },
    ],
  },
];

export function getTemplateById(id: string): CanvasTemplate | undefined {
  return CANVAS_TEMPLATES.find((t) => t.id === id);
}
